"""001_initial_schema

Revision ID: c845aee3c751
Revises:
Create Date: 2026-06-21 16:56:12.046574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import JSONB

# Import pgvector type
try:
    from pgvector.sqlalchemy import Vector
except ImportError:
    # Fallback if pgvector not available
    Vector = sa.Text


# revision identifiers, used by Alembic.
revision: str = 'c845aee3c751'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create pgvector extension
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('design_templates',
    sa.Column('template_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('glb_url', sa.String(length=500), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=False),
    sa.Column('embedding', Vector(1536), nullable=True),
    sa.Column('default_params', JSONB(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('template_id')
    )
    op.create_table('idempotency_keys',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('resource_id', sa.String(length=36), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('response_body', JSONB(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index('idx_idempotency_expires', 'idempotency_keys', ['expires_at'], unique=False)
    op.create_table('studios',
    sa.Column('studio_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=50), nullable=False),
    sa.Column('specialties', JSONB(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('current_load', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('price_range_min', sa.Float(), nullable=False),
    sa.Column('price_range_max', sa.Float(), nullable=False),
    sa.Column('estimated_days', sa.Integer(), nullable=False),
    sa.Column('craft_overrides', JSONB(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('studio_id')
    )
    op.create_table('tasks',
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('payload', JSONB(), nullable=False),
    sa.Column('result_uri', sa.String(length=500), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_index('idx_tasks_created', 'tasks', ['created_at'], unique=False)
    op.create_index('idx_tasks_state', 'tasks', ['state'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('phone_hash', sa.String(length=64), nullable=False),
    sa.Column('phone_encrypted', sa.Text(), nullable=False),
    sa.Column('email_encrypted', sa.Text(), nullable=True),
    sa.Column('address_encrypted', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_phone_hash'), 'users', ['phone_hash'], unique=True)
    op.create_table('sessions',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_table('studio_craft_overrides',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('studio_id', sa.String(length=36), nullable=False),
    sa.Column('min_wall_thickness', sa.Float(), nullable=True),
    sa.Column('actual_shrinkage_rate', sa.Float(), nullable=True),
    sa.Column('max_overhang_angle', sa.Float(), nullable=True),
    sa.Column('calibration_data', JSONB(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['studio_id'], ['studios.studio_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('designs',
    sa.Column('design_id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('design_params', JSONB(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ),
    sa.PrimaryKeyConstraint('design_id')
    )
    op.create_table('session_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('design_params', JSONB(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('design_versions',
    sa.Column('version_id', sa.String(length=36), nullable=False),
    sa.Column('design_id', sa.String(length=36), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('option_no', sa.Integer(), nullable=False),
    sa.Column('pipeline', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('glb_url', sa.String(length=500), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=False),
    sa.Column('craft_check_result', JSONB(), nullable=False),
    sa.Column('estimated_volume', sa.Float(), nullable=False),
    sa.Column('estimated_weight', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('estimated_days', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['design_id'], ['designs.design_id'], ),
    sa.PrimaryKeyConstraint('version_id')
    )
    op.create_table('orders',
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('option_id', sa.String(length=36), nullable=False),
    sa.Column('studio_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('idempotency_key', sa.String(length=64), nullable=False),
    sa.Column('shipping_name', sa.String(length=100), nullable=False),
    sa.Column('shipping_phone', sa.String(length=20), nullable=False),
    sa.Column('shipping_address', sa.String(length=500), nullable=False),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.Column('workorder_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['option_id'], ['design_versions.version_id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ),
    sa.ForeignKeyConstraint(['studio_id'], ['studios.studio_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('order_id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_table('order_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('from_status', sa.String(length=30), nullable=True),
    sa.Column('to_status', sa.String(length=30), nullable=False),
    sa.Column('operator', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('extra_data', JSONB(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    # Create ivfflat index for vector similarity search
    op.execute("""
        CREATE INDEX IF NOT EXISTS idx_design_templates_embedding
        ON design_templates
        USING ivfflat (embedding vector_cosine_ops)
        WITH (lists = 100)
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop ivfflat index
    op.execute('DROP INDEX IF EXISTS idx_design_templates_embedding')

    op.drop_table('order_logs')
    op.drop_table('orders')
    op.drop_table('design_versions')
    op.drop_table('session_messages')
    op.drop_table('designs')
    op.drop_table('studio_craft_overrides')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_users_phone_hash'), table_name='users')
    op.drop_table('users')
    op.drop_index('idx_tasks_state', table_name='tasks')
    op.drop_index('idx_tasks_created', table_name='tasks')
    op.drop_table('tasks')
    op.drop_table('studios')
    op.drop_index('idx_idempotency_expires', table_name='idempotency_keys')
    op.drop_table('idempotency_keys')
    op.drop_table('design_templates')
    # ### end Alembic commands ###
